/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:78438b9a-840c-495b-8dd3-a72acb3e3f0a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_APa5urVhu",
    "aws_user_pools_web_client_id": "3dusi1ac1ofusdjbufvalqvmpq",
    "oauth": {}
};


export default awsmobile;
